[platformio]
extra_configs = ../deps/bmv080_sdk.ini, ../deps/bsec3_lib.ini

[env:polverine]
platform = espressif32@6.11.0
board = polverine
framework = espidf
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
build_flags =
    -std=gnu17
    -Wall
    -mlongcalls
    -Wno-frame-address
    -O2
    ${bmv080_sdk.build_flags}
    ${bsec3_lib.build_flags}

build_src_filter =
    +<*>
    ${bsec3_lib.build_src_filter}
    +<../../deps/bosch-sensortec/bsec_library_wrappers/bsec_integration.c>
